
package com.hoo.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IComplexUserService", targetNamespace = "http://service.hoo.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IComplexUserService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void setUser(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getUserByName(
        @WebParam(name = "name", partName = "name")
        String name);

}
